// SU - shared-ui
// CA - client-app
const notificationId = {
    SU_CA_DEVICE_DETAIL_PAGE_OWN_CHANGE: 'SU_CA_DEVICE_DETAIL_PAGE_OWN_CHANGE',
    SU_CA_HANDLE_OWN_DEVICES_ERRORS: 'SU_CA_HANDLE_OWN_DEVICES_ERRORS',
    SU_CA_HANDLE_UPDATE_RESOURCE_ERRORS: 'SU_CA_HANDLE_UPDATE_RESOURCE_ERRORS',
    SU_CA_HANDLE_UPDATE_RESOURCE_ERRORS_DEADLINE_EXCEEDED: 'SU_CA_HANDLE_UPDATE_RESOURCE_ERRORS_DEADLINE_EXCEEDED',
    SU_CA_HANDLE_UPDATE_RESOURCE_ERRORS_COMMAND_EXPIRED: 'SU_CA_HANDLE_UPDATE_RESOURCE_ERRORS_COMMAND_EXPIRED',
    SU_CA_HANDLE_UPDATE_RESOURCE_ERRORS_INVALID_ARGUMENT: 'SU_CA_HANDLE_UPDATE_RESOURCE_ERRORS_INVALID_ARGUMENT',
    SU_CA_HANDLE_DELETE_DEVICES_ERRORS: 'SU_CA_HANDLE_DELETE_DEVICES_ERRORS',
    SU_CA_HANDLE_FETCH_RESOURCE_ERRORS: 'SU_CA_HANDLE_FETCH_RESOURCE_ERRORS',
    SU_CA_HANDLE_SHADOW_SYNCHRONIZATION_ERRORS_DEADLINE_EXCEEDED: 'SU_CA_HANDLE_SHADOW_SYNCHRONIZATION_ERRORS_DEADLINE_EXCEEDED',
    SU_CA_HANDLE_SHADOW_SYNCHRONIZATION_ERRORS: 'SU_CA_HANDLE_SHADOW_SYNCHRONIZATION_ERRORS',
    SU_CA_HANDLE_CREATE_RESOURCE_ERRORS: 'SU_CA_HANDLE_CREATE_RESOURCE_ERRORS',
    SU_CA_HANDLE_CREATE_RESOURCE_ERRORS_INVALID_ARGUMENT: 'SU_CA_HANDLE_CREATE_RESOURCE_ERRORS_INVALID_ARGUMENT',
    SU_CA_HANDLE_CREATE_RESOURCE_ERRORS_COMMAND_EXPIRED: 'SU_CA_HANDLE_CREATE_RESOURCE_ERRORS_COMMAND_EXPIRED',
    SU_CA_HANDLE_CREATE_RESOURCE_ERRORS_DEADLINE_EXCEEDED: 'SU_CA_HANDLE_CREATE_RESOURCE_ERRORS_DEADLINE_EXCEEDED',
    SU_CA_HANDLE_DELETE_RESOURCE_ERRORS: 'SU_CA_HANDLE_DELETE_RESOURCE_ERRORS',
    SU_CA_HANDLE_DELETE_RESOURCE_ERRORS_DEADLINE_EXCEEDED: 'SU_CA_HANDLE_DELETE_RESOURCE_ERRORS_DEADLINE_EXCEEDED',
    SU_CA_HANDLE_DELETE_RESOURCE_ERRORS_COMMAND_EXPIRED: 'SU_CA_HANDLE_DELETE_RESOURCE_ERRORS_COMMAND_EXPIRED',
    SU_CA_ONBOARD_DEVICE: 'SU_CA_ONBOARD_DEVICE',
    SU_CA_UPDATE_DEVICE_NAME: 'SU_CA_UPDATE_DEVICE_NAME',
    SU_CA_DEVICE_DETAIL_TAB2_CREATE_RESOURCE: 'SU_CA_DEVICE_DETAIL_TAB2_CREATE_RESOURCE',
    SU_CA_DEVICE_DETAIL_TAB_2_UPDATE_RESOURCE: 'SU_CA_DEVICE_DETAIL_TAB_2_UPDATE_RESOURCE',
    SU_CA_DEVICE_DETAIL_TAB_2_DELETE_RESOURCE: 'SU_CA_DEVICE_DETAIL_TAB_2_DELETE_RESOURCE',
    SU_CA_DEVICE_LIST_DEVICE_ERROR: 'SU_CA_DEVICE_LIST_DEVICE_ERROR',
    SU_CA_DEVICE_LIST_DELETE_DEVICES: 'SU_CA_DEVICE_LIST_DELETE_DEVICES',
    SU_CA_DEVICE_LIST_HANDLE_OWN_DEVICE: 'SU_CA_DEVICE_LIST_HANDLE_OWN_DEVICE',
    SU_CA_DEVICE_LIST_HANDLE_UPDATE_RESOURCE: 'SU_CA_DEVICE_LIST_HANDLE_UPDATE_RESOURCE',
    SU_CA_FIND_NEW_DEVICE_BY_IP_FETCH: 'SU_CA_FIND_NEW_DEVICE_BY_IP_FETCH',
}

export default notificationId
