const esModules = ['react-merge-refs', 'swiper', 'units-converter'].join('|')

module.exports = {
    preset: 'ts-jest',
    testEnvironment: 'jsdom',
    moduleNameMapper: {
        'react-merge-refs': '<rootDir>/config/jest.reactMergeRefMock.js',
        '\\.svg$': '<rootDir>/config/jest.svgMock.js',
        // '\\.(css|less)$': 'identity-obj-proxy',
        '\\.(gif|ttf|eot|svg)$': '<rootDir>/config/fileMock.js',
        '\\.(css|less|jpg|jpeg|png)$': '<rootDir>/config/styleMock.js',
        'units-converter': '<rootDir>/config/moduleMock.js',
        'typeface-nunito': 'identity-obj-proxy',
    },
    clearMocks: true,
    collectCoverage: false,
    rootDir: process.cwd(),
    roots: ['<rootDir>/src'],
    collectCoverageFrom: ['src/**/*.{js,jsx,ts,tsx}', '!node_modules/**'],
    coverageReporters: ['json', 'text', 'lcov', 'clover', 'cobertura'],
    moduleDirectories: ['node_modules'],
    modulePaths: ['<rootDir>'],
    moduleFileExtensions: ['js', 'jsx', 'ts', 'tsx'],
    resetMocks: true,
    setupFiles: ['react-app-polyfill/jsdom'],
    setupFilesAfterEnv: ['<rootDir>/config/jest.setup.ts'],
    snapshotSerializers: ['@emotion/jest/serializer'],
    testMatch: ['<rootDir>/src/**/*.test.{js,jsx,ts,tsx}'],
    transformIgnorePatterns: [`/node_modules/(?!${esModules})`],
    testResultsProcessor: 'jest-sonar-reporter',
    transform: {
        '^.+.(js|jsx|ts|tsx)$': ['babel-jest'],
        '\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$': '<rootDir>/config/fileTransformer.js',
    },
    verbose: true,
    watchPlugins: ['jest-watch-typeahead/filename', 'jest-watch-typeahead/testname'],
}
